from __future__ import annotations

from dataclasses import dataclass
import os

from dotenv import load_dotenv


@dataclass(frozen=True)
class Settings:
    user_lat: float
    user_lon: float
    adsbfi_base: str
    search_radius_nm: float
    poll_interval_seconds: int
    prediction_horizon_seconds: int
    prediction_step_seconds: int
    prediction_use_history_fit: bool
    prediction_fit_window_seconds: int
    prediction_fit_min_points: int
    max_observer_relocation_km: float
    travel_speed_kmh: float
    reach_safety: float
    min_lead_time_seconds: int
    preferred_lead_time_seconds: int
    alert_ready_lead_time_seconds: int
    min_altitude_ft: float
    soft_good_altitude_ft: float
    airport_exclusion_nm: float
    airport_traffic_filters: str
    max_vertical_rate_stable_fpm: float
    allow_stable_vertical_trend: bool
    max_stable_vertical_rate_fpm: float
    max_vertical_rate_variation_fpm: float
    stable_vertical_trend_min_points: int
    max_track_change_60s_deg: float
    max_gs_change_60s_kt: float
    alert_min_score: float
    max_offset_body_diameters_for_alert: float
    min_body_elevation_deg: float
    min_body_elevation_deg_for_candidate: float
    observation_candidate_max_separation_deg: float
    observation_candidate_min_score: float
    observation_candidate_max_lead_seconds: int
    notification_require_convergence: bool
    early_notification_consecutive_cycles: int
    notification_consecutive_cycles: int
    notification_max_time_shift_seconds: float
    notification_max_observer_shift_km: float
    notification_max_offset_worsening_diameters: float
    telegram_candidate_cooldown_seconds: int
    telegram_max_candidates_per_cycle: int
    telegram_update_cooldown_seconds: int
    telegram_update_min_distance_improvement_km: float
    telegram_update_min_offset_improvement_ratio: float
    alert_notifications_enabled: bool
    alert_service_poll_interval_seconds: int
    alert_service_candidate_lookback_seconds: int
    transit_validation_enabled: bool
    transit_validation_delay_seconds: int
    transit_validation_observation_window_seconds: int
    transit_validation_max_wait_seconds: int
    transit_validation_uncertainty_diameters: float
    standby_body_elevation_deg: float
    min_stability_score_for_geometry: float
    min_aircraft_elevation_deg_for_geometry: float
    max_aircraft_range_km_for_geometry: float
    locked_alert_window_seconds: int
    run_mode: str
    log_level: str
    log_to_file: bool
    log_dir: str
    log_retain_full_days: int
    log_retain_compressed_days: int
    log_emergency_free_mb: int
    data_retention_enabled: bool
    data_retention_interval_seconds: int
    data_retention_observations_hours: int
    data_retention_rejected_candidate_days: int
    data_retention_interesting_candidate_days: int
    data_retention_prediction_run_days: int
    data_retention_trajectory_snapshot_days: int
    data_retention_emergency_free_mb: int
    data_retention_emergency_observations_hours: int
    data_retention_emergency_rejected_candidate_days: int
    data_retention_delete_batch_size: int
    ui_enabled: bool
    ui_host: str
    ui_port: int
    database_url: str
    postgres_host: str
    postgres_port: int
    postgres_db: str
    postgres_user: str
    postgres_password: str


def _get_bool(name: str, default: bool) -> bool:
    return os.getenv(name, str(default)).lower() in {"1", "true", "yes", "on"}


def load_settings() -> Settings:
    load_dotenv()
    return Settings(
        user_lat=float(os.getenv("USER_LAT", "52.0")),
        user_lon=float(os.getenv("USER_LON", "21.0")),
        adsbfi_base=os.getenv("ADSBFI_BASE", "https://opendata.adsb.fi/api").rstrip("/"),
        search_radius_nm=float(os.getenv("SEARCH_RADIUS_NM", "120")),
        poll_interval_seconds=int(os.getenv("POLL_INTERVAL_SECONDS", "10")),
        prediction_horizon_seconds=int(os.getenv("PREDICTION_HORIZON_SECONDS", "1800")),
        prediction_step_seconds=int(os.getenv("PREDICTION_STEP_SECONDS", "1")),
        prediction_use_history_fit=_get_bool("PREDICTION_USE_HISTORY_FIT", True),
        prediction_fit_window_seconds=int(os.getenv("PREDICTION_FIT_WINDOW_SECONDS", "90")),
        prediction_fit_min_points=int(os.getenv("PREDICTION_FIT_MIN_POINTS", "4")),
        max_observer_relocation_km=float(os.getenv("MAX_OBSERVER_RELOCATION_KM", "12")),
        travel_speed_kmh=float(os.getenv("TRAVEL_SPEED_KMH", "50")),
        reach_safety=float(os.getenv("REACH_SAFETY", "0.8")),
        min_lead_time_seconds=int(os.getenv("MIN_LEAD_TIME_SECONDS", "600")),
        preferred_lead_time_seconds=int(os.getenv("PREFERRED_LEAD_TIME_SECONDS", "900")),
        alert_ready_lead_time_seconds=int(os.getenv("ALERT_READY_LEAD_TIME_SECONDS", "300")),
        min_altitude_ft=float(os.getenv("MIN_ALTITUDE_FT", "12000")),
        soft_good_altitude_ft=float(os.getenv("SOFT_GOOD_ALTITUDE_FT", "18000")),
        airport_exclusion_nm=float(os.getenv("AIRPORT_EXCLUSION_NM", "20")),
        airport_traffic_filters=os.getenv("AIRPORT_TRAFFIC_FILTERS", "EPWA:strict:35,EPMO:soft:12"),
        max_vertical_rate_stable_fpm=float(os.getenv("MAX_VERTICAL_RATE_STABLE_FPM", "500")),
        allow_stable_vertical_trend=_get_bool("ALLOW_STABLE_VERTICAL_TREND", True),
        max_stable_vertical_rate_fpm=float(os.getenv("MAX_STABLE_VERTICAL_RATE_FPM", "3000")),
        max_vertical_rate_variation_fpm=float(os.getenv("MAX_VERTICAL_RATE_VARIATION_FPM", "600")),
        stable_vertical_trend_min_points=int(os.getenv("STABLE_VERTICAL_TREND_MIN_POINTS", "4")),
        max_track_change_60s_deg=float(os.getenv("MAX_TRACK_CHANGE_60S_DEG", "8")),
        max_gs_change_60s_kt=float(os.getenv("MAX_GS_CHANGE_60S_KT", "40")),
        alert_min_score=float(os.getenv("ALERT_MIN_SCORE", "0.70")),
        max_offset_body_diameters_for_alert=float(os.getenv("MAX_OFFSET_BODY_DIAMETERS_FOR_ALERT", "0.25")),
        min_body_elevation_deg=float(os.getenv("MIN_BODY_ELEVATION_DEG", "8")),
        min_body_elevation_deg_for_candidate=float(os.getenv("MIN_BODY_ELEVATION_DEG_FOR_CANDIDATE", "0")),
        observation_candidate_max_separation_deg=float(os.getenv("OBSERVATION_CANDIDATE_MAX_SEPARATION_DEG", "0.20")),
        observation_candidate_min_score=float(os.getenv("OBSERVATION_CANDIDATE_MIN_SCORE", "0.65")),
        observation_candidate_max_lead_seconds=int(os.getenv("OBSERVATION_CANDIDATE_MAX_LEAD_SECONDS", "600")),
        notification_require_convergence=_get_bool("NOTIFICATION_REQUIRE_CONVERGENCE", True),
        early_notification_consecutive_cycles=int(os.getenv("EARLY_NOTIFICATION_CONSECUTIVE_CYCLES", "2")),
        notification_consecutive_cycles=int(os.getenv("NOTIFICATION_CONSECUTIVE_CYCLES", "3")),
        notification_max_time_shift_seconds=float(os.getenv("NOTIFICATION_MAX_TIME_SHIFT_SECONDS", "5")),
        notification_max_observer_shift_km=float(os.getenv("NOTIFICATION_MAX_OBSERVER_SHIFT_KM", "0.5")),
        notification_max_offset_worsening_diameters=float(os.getenv("NOTIFICATION_MAX_OFFSET_WORSENING_DIAMETERS", "0.05")),
        telegram_candidate_cooldown_seconds=int(os.getenv("TELEGRAM_CANDIDATE_COOLDOWN_SECONDS", "900")),
        telegram_max_candidates_per_cycle=int(os.getenv("TELEGRAM_MAX_CANDIDATES_PER_CYCLE", "2")),
        telegram_update_cooldown_seconds=int(os.getenv("TELEGRAM_UPDATE_COOLDOWN_SECONDS", "180")),
        telegram_update_min_distance_improvement_km=float(os.getenv("TELEGRAM_UPDATE_MIN_DISTANCE_IMPROVEMENT_KM", "0.5")),
        telegram_update_min_offset_improvement_ratio=float(os.getenv("TELEGRAM_UPDATE_MIN_OFFSET_IMPROVEMENT_RATIO", "0.30")),
        alert_notifications_enabled=_get_bool("ALERT_NOTIFICATIONS_ENABLED", True),
        alert_service_poll_interval_seconds=int(os.getenv("ALERT_SERVICE_POLL_INTERVAL_SECONDS", "5")),
        alert_service_candidate_lookback_seconds=int(os.getenv("ALERT_SERVICE_CANDIDATE_LOOKBACK_SECONDS", "900")),
        transit_validation_enabled=_get_bool("TRANSIT_VALIDATION_ENABLED", True),
        transit_validation_delay_seconds=int(os.getenv("TRANSIT_VALIDATION_DELAY_SECONDS", "45")),
        transit_validation_observation_window_seconds=int(os.getenv("TRANSIT_VALIDATION_OBSERVATION_WINDOW_SECONDS", "90")),
        transit_validation_max_wait_seconds=int(os.getenv("TRANSIT_VALIDATION_MAX_WAIT_SECONDS", "300")),
        transit_validation_uncertainty_diameters=float(os.getenv("TRANSIT_VALIDATION_UNCERTAINTY_DIAMETERS", "0.10")),
        standby_body_elevation_deg=float(os.getenv("STANDBY_BODY_ELEVATION_DEG", "5")),
        min_stability_score_for_geometry=float(os.getenv("MIN_STABILITY_SCORE_FOR_GEOMETRY", "0.65")),
        min_aircraft_elevation_deg_for_geometry=float(os.getenv("MIN_AIRCRAFT_ELEVATION_DEG_FOR_GEOMETRY", "7.5")),
        max_aircraft_range_km_for_geometry=float(os.getenv("MAX_AIRCRAFT_RANGE_KM_FOR_GEOMETRY", "120")),
        locked_alert_window_seconds=int(os.getenv("LOCKED_ALERT_WINDOW_SECONDS", "600")),
        run_mode=os.getenv("RUN_MODE", "quiet"),
        log_level=os.getenv("LOG_LEVEL", "INFO"),
        log_to_file=_get_bool("LOG_TO_FILE", True),
        log_dir=os.getenv("LOG_DIR", "./logs"),
        log_retain_full_days=int(os.getenv("LOG_RETAIN_FULL_DAYS", "3")),
        log_retain_compressed_days=int(os.getenv("LOG_RETAIN_COMPRESSED_DAYS", "10")),
        log_emergency_free_mb=int(os.getenv("LOG_EMERGENCY_FREE_MB", "1536")),
        data_retention_enabled=_get_bool("DATA_RETENTION_ENABLED", True),
        data_retention_interval_seconds=int(os.getenv("DATA_RETENTION_INTERVAL_SECONDS", "3600")),
        data_retention_observations_hours=int(os.getenv("DATA_RETENTION_OBSERVATIONS_HOURS", "48")),
        data_retention_rejected_candidate_days=int(os.getenv("DATA_RETENTION_REJECTED_CANDIDATE_DAYS", "7")),
        data_retention_interesting_candidate_days=int(os.getenv("DATA_RETENTION_INTERESTING_CANDIDATE_DAYS", "30")),
        data_retention_prediction_run_days=int(os.getenv("DATA_RETENTION_PREDICTION_RUN_DAYS", "14")),
        data_retention_trajectory_snapshot_days=int(os.getenv("DATA_RETENTION_TRAJECTORY_SNAPSHOT_DAYS", "30")),
        data_retention_emergency_free_mb=int(os.getenv("DATA_RETENTION_EMERGENCY_FREE_MB", "1536")),
        data_retention_emergency_observations_hours=int(os.getenv("DATA_RETENTION_EMERGENCY_OBSERVATIONS_HOURS", "24")),
        data_retention_emergency_rejected_candidate_days=int(os.getenv("DATA_RETENTION_EMERGENCY_REJECTED_CANDIDATE_DAYS", "3")),
        data_retention_delete_batch_size=int(os.getenv("DATA_RETENTION_DELETE_BATCH_SIZE", "50000")),
        ui_enabled=_get_bool("UI_ENABLED", True),
        ui_host=os.getenv("UI_HOST", "0.0.0.0"),
        ui_port=int(os.getenv("UI_PORT", "9999")),
        database_url=os.getenv("DATABASE_URL", "postgresql://aircraft:aircraft@postgres:5432/aircraft_transit"),
        postgres_host=os.getenv("POSTGRES_HOST", "postgres"),
        postgres_port=int(os.getenv("POSTGRES_PORT", "5432")),
        postgres_db=os.getenv("POSTGRES_DB", "aircraft_transit"),
        postgres_user=os.getenv("POSTGRES_USER", "aircraft"),
        postgres_password=os.getenv("POSTGRES_PASSWORD", "aircraft"),
    )
